using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class GameOjbectSendMessage : MonoBehaviour
{
    // 消息的发送和接收
    //BroadcastMessage 效果榈饔么擞蜗范韵蠡蛉魏巫酉畹拿扛MonoBehavior上名为methodName的方法
    #region
    public  void Print(float damage)
    {
        print(damage);
    }
    public  void SendMessage()
    {
        //gameObject.BroadcastMessage("Print", 5.0f);
        gameObject.BroadcastMessage("Attack", null, SendMessageOptions.DontRequireReceiver);
        gameObject.SendMessage("Print", 5.0f);
    }
    #endregion
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        if (Input.GetKeyDown(KeyCode.Space))
            SendMessage();
    }
}
